// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwiwrphpwiwrsgtxamqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3aXdycGhwd2l3cnNndHhhbXF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNzI1NTIsImV4cCI6MjA2ODc0ODU1Mn0.-JqoaOjcGT_0jzih7qQKL5BPvKbpdGXfqVtculoQ-QY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});